name: Planck Android app pipeline linux
run-name: ${{ github.actor }} is building the Planck Android app
on: [push]
jobs:
  Build-Android-On-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.ALL_REPO_ACCESS_TOKEN }}
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -r ${{ github.workspace }}/core
      # dependencies
      - run: lsb_release -a
      - run: sudo add-apt-repository universe -y
      - run: sudo add-apt-repository multiverse -y
      - run: sudo apt-get update -yqq
      - run: sudo apt search capnproto
      - run: sudo apt search ant
      - run: sudo apt-get install -yqq apt-utils git clang libclang-dev make pkg-config nettle-dev libssl-dev \
          capnproto libsqlite3-dev build-essential curl wget software-properties-common libtool patch \
              ant/jammy gettext unzip vim bash-completion autoconf automake cargo android-sdk* locales

      - run: sudo apt-get install -yqq python3 python3-lxml-dbg python3-lxml python3-distutils-extra
      - run: sudo apt-get install -yqq asn1c
      - run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
      - run: curl https://sh.rustup.rs -sSf | bash -s -- --default-toolchain 1.64.0 -y
      - run: echo "ğŸ This job's status is ${{ job.status }}."